version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  db:
    image: postgres:13
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER} # superuser
      - POSTGRES_PASSWORD=${DB_PASSWORD} # superuser password
      - POSTGRES_DB=${DB_NAME} # default database, if not specified POSTGRES_USER will be used
    volumes:
      - postgres_data_apidb:/var/lib/postgresql/data

volumes:
  postgres_data_apidb:
