"""Add new columns to users table

Revision ID: 50b81df847f1
Revises: e532e3ebd132
Create Date: 2024-08-21 10:08:25.382980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = "50b81df847f1"
down_revision: Union[str, None] = "e532e3ebd132"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()

    op.add_column("users", sa.Column("first_name", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("email", sa.String(length=100), nullable=True))
    op.add_column(
        "users", sa.Column("password_hash", sa.String(length=1000), nullable=True)
    )

    conn.execute(
        text(
            """
            UPDATE users
            SET first_name='', last_name='', email='', password_hash='';
            """
        )
    )

    op.alter_column("users", "first_name", nullable=False)
    op.alter_column("users", "last_name", nullable=False)
    op.alter_column("users", "email", nullable=False)
    op.alter_column("users", "password_hash", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    op.drop_column("users", "email")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
