"""change role_id column is not null

Revision ID: 5353a8b6e181
Revises: 3fb4bf68d0bd
Create Date: 2024-08-29 23:35:12.079386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5353a8b6e181"
down_revision: Union[str, None] = "3fb4bf68d0bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
